#!/bin/bash -login

set -o nounset
set -o errexit
set -o pipefail

FILEPATH="/mnt/scratch/tg/irberlui/biodata/galGal/outputs/moleculo/LR6000017-DNA_A01-LRAAA-1_LongRead_500_1499nt.fasta"
WORKDIR=/mnt/scratch/tg/irberlui/2014-hll-counter/workdir

mkdir -p $WORKDIR/output/

write_submit_script() {
  local SCRIPT=$1
  local FILEPATH=$2
  local FILENAME=$(basename $FILEPATH)
  local MINUTES=$3
  local MEM=$4
  local REPLICATE=$5

  mkdir -p $WORKDIR/output/${REPLICATE}
  cat <<EOT1> $WORKDIR/${SCRIPT}-${FILENAME}
#!/bin/bash -login
#PBS -l walltime=00:$MINUTES:00,nodes=1:ppn=1
#PBS -l mem=$MEM
#PBS -j oe
#PBS -o $WORKDIR/output/${REPLICATE}/log.${SCRIPT}.${FILENAME}
#PBS -N hll.${FILENAME}
#PBS -A ged-intel11
#PBS -W umask=027
#PBS -t 00-13

set -o nounset
set -o errexit
set -o pipefail

module use /opt/software/ged-software/modulefiles/
module load anaconda

set -x

cd \$PBS_O_WORKDIR

KSIZE=\$((31 + \$PBS_ARRAYID * 16))
python $SCRIPT $FILEPATH \$KSIZE

cat \${PBS_NODEFILE}       # Output Contents of the PBS NODEFILE

env | grep PBS            # Print out values of the current jobs PBS environment variables

qstat -f \${PBS_JOBID}     # Print out final statistics about resource uses before job exits
EOT1

}

SCRIPT="unique_kmers_hll.py"
for replicate in $(seq -w 01 30)
do
  write_submit_script $SCRIPT $FILEPATH 10 100mb r${replicate}
  qsub $WORKDIR/${SCRIPT}-$(basename ${FILEPATH})
done

#SCRIPT="unique_kmers_exact.py"
#write_submit_script $SCRIPT $FILEPATH 20 20gb r${replicate}
#qsub $WORKDIR/${SCRIPT}-$(basename ${FILEPATH})
